Update Semantic Kernel to 1.6.2 to fix issue with `JsonSchema.Net.Generation` package to resolve dependency conflict
Encamina/enmarcha pull request #100
Opened 2024-03-15 17:59 UTC by rliberoff

Update Semantic Kernel to 1.6.2 to fix issue with `JsonSchema.Net.Generation` package to resolve dependency conflict.

2024-03-15 21:05 UTC, LuisM000 approved these changes

2024-03-15 21:09 UTC, LuisM000 requested changes
Perhaps we should update the changelog :)

2024-03-17 11:38 UTC, adiazcan approved these changes, later dismissed

2024-03-18 07:39 UTC, rliberoff commented
> Perhaps we should update the changelog :)

Done! 👍🏻

2024-03-18 07:59 UTC, LuisM000 approved these changes

2024-03-18 19:09 UTC, MarioRamosEs approved these changes

2024-03-18 19:09 UTC, merged