Fixed warnings CS8603 and CS8625 in Encamina.Enmarcha.AspNet
Encamina/enmarcha pull request #112
Opened 2024-04-29 08:44 UTC by HugoRamosEs

2024-04-29 09:03 UTC, MarioRamosEs requested changes

2024-04-29 09:03 UTC, MarioRamosEs commented on src/Encamina.Enmarcha.AspNet.Mvc/Bindings/CustomDateTimeModelBinderProvider.cs
> +    public CustomDateTimeModelBinderProvider() : this(null!)
In this case, I would make `customDateTimeFormat` nullable (along with all necessary changes) and remove this `!`

2024-04-29 09:25 UTC, MarioRamosEs requested changes

2024-04-29 09:25 UTC, MarioRamosEs commented on src/Encamina.Enmarcha.AspNet.Mvc/Bindings/CustomDateTimeModelBinderProvider.cs
> +    private readonly string? customDateTimeFormat;
This change has generated a new warning on line 33 `? new CustomDateTimeModelBinder(customDateTimeFormat)`.

We should also change `CustomDateTimeModelBinder` to accept `null` in the `customDateTimeFormat` parameter (and property)

2024-04-29 09:58 UTC, MarioRamosEs approved these changes

2024-05-02 15:32 UTC, LuisM000 approved these changes

2024-05-02 15:32 UTC, merged