Final 8.1.7 release
Encamina/enmarcha pull request #128
Opened 2024-08-06 11:12 UTC by MarioRamosEs

With this PR we release the final version `8.1.7`, updating packages with vulnerabilities and leaving the preview versions for the upcoming semi-breaking changes.

2024-08-06 11:25 UTC, albertodiazencamina approved these changes, later dismissed

2024-08-06 11:26 UTC, LuisM000 commented
Perhaps we should update the CHANGELOG.md file to reflect the new versions of the NuGet packages that have been updated :)

2024-08-06 11:27 UTC, LuisM000 requested changes
Perhaps we should update the CHANGELOG.md file to reflect the new versions of the NuGet packages that have been updated. :)

2024-08-06 11:38 UTC, MarioRamosEs commented
> Perhaps we should update the CHANGELOG.md file to reflect the new versions of the NuGet packages that have been updated. :)

Well spotted! updated

2024-08-06 11:39 UTC, LuisM000 approved these changes

2024-08-07 12:01 UTC, VictorMuMo approved these changes

2024-08-07 12:01 UTC, merged