Fix issue #34. Semantic kernel summaries plugin fails to preserve the original language of the text
Encamina/enmarcha pull request #36
Opened 2023-12-20 09:09 UTC by LuisM000

This is a pick from https://github.com/Encamina/enmarcha/pull/35 fixed in https://github.com/Encamina/enmarcha/issues/34.

2023-12-20 10:10 UTC, LuisM000 commented
I didn't notice this commented-out section
https://github.com/Encamina/enmarcha/blob/48e6f7508760648fde5678da64a0e167dabb99ff/.github/workflows/main.yml#L92
and the NuGets have been generated 😞

2023-12-21 14:14 UTC, rliberoff requested changes

2023-12-21 14:14 UTC, rliberoff commented on src/Encamina.Enmarcha.SemanticKernel.Plugins.Text/PluginsInfo.cs
> +                    /// The name of the «locale» parameter, which represents the language in which the summary will be generated.
There are some weird `Â` characters in the code. Could you please check them?

2023-12-21 15:50 UTC, rliberoff approved these changes

2023-12-21 15:50 UTC, rliberoff commented on src/Encamina.Enmarcha.SemanticKernel.Plugins.Text/PluginsInfo.cs
> +                    /// The name of the «locale» parameter, which represents the language in which the summary will be generated.
They also appear in the comments of the `MaxWordsCount` property.

2023-12-21 15:50 UTC, rliberoff commented on src/Encamina.Enmarcha.SemanticKernel.Plugins.Text/PluginsInfo.cs
> +                    /// The name of the «locale» parameter, which represents the language in which the summary will be generated.
![image](https://github.com/Encamina/enmarcha/assets/5644891/4bb4e351-4191-480d-af68-fdff00d883de)

2023-12-21 15:51 UTC, merged