Added optional parameter to `AddDefaultDocumentConnectorProvider` and `AddDefaultDocumentContentExtractor`
Encamina/enmarcha pull request #57
Opened 2024-01-19 19:46 UTC by fjbelizon

Added optional parameter to `AddDefaultDocumentConnectorProvider` and `AddDefaultDocumentContentExtractor` to pass it a function to calculate the length of a text and inject it as a dependency.

2024-01-19 20:31 UTC, VictorMuMo submitted a review, later dismissed

2024-01-22 08:09 UTC, VictorMuMo submitted a review, later dismissed

2024-01-22 09:01 UTC, rliberoff requested changes

2024-01-22 09:01 UTC, rliberoff commented on src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Extensions/IServiceCollectionExtensions.cs
> +    public static IServiceCollection AddDefaultDocumentConnectorProvider(this IServiceCollection services, Func<string, int> lengthCountFunction = null)
I would create an overloading method instead, as suggested by SonarCloud rule RSPEC-2360 (https://rules.sonarsource.com/csharp/RSPEC-2360/). 

We use optional parameters when there is no other alternative to preserve backwards compatibility or when we are forced due to changes in the architecture of any underlaying library (like what happened with SK).

That being said, the end code should look like a new method that takes the `lengthFunction` as a mandatory parameter still allowing it to be `null`. The original method then calls the new overload by sending the `lengthFunction` as `null`. The body of the overloaded method will be the same code you have here.

2024-01-22 09:01 UTC, rliberoff commented on src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Extensions/IServiceCollectionExtensions.cs
> +    public static IServiceCollection AddDefaultDocumentConnectorProvider(this IServiceCollection services, Func<string, int> lengthCountFunction = null)
@fjbelizon 🛎️

2024-01-22 09:19 UTC, fjbelizon commented on src/Encamina.Enmarcha.SemanticKernel.Connectors.Document/Extensions/IServiceCollectionExtensions.cs
> +    public static IServiceCollection AddDefaultDocumentConnectorProvider(this IServiceCollection services, Func<string, int> lengthCountFunction = null)
The methods are overloaded now. Thanks by your comments.

2024-01-22 09:35 UTC, rliberoff approved these changes

2024-01-22 09:35 UTC, merged